name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    env:
      VENVDIR: /tmp/.venv
      BUNDLE_PATH: /tmp/.gems
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Cache Setup"
      id: cache-setup
      run: |
        mkdir -p "$HOME"/.cache/xml2rfc
        echo "::set-output name=path::$HOME/.cache/xml2rfc"
        date -u "+::set-output name=date::%FT%T"

    - name: "Cache venv"
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.VENVDIR }}
          ${{ env.BUNDLE_PATH }}
        key: venvcache-${{ steps.cache-setup.outputs.date }}
        restore-keys: |
          venvcache-${{ steps.cache-setup.outputs.date }}
          venvcache-

    - name: "Cache References"
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.cache-setup.outputs.path }}
          .targets.mk
        key: refcache-${{ steps.cache-setup.outputs.date }}
        restore-keys: |
          refcache-${{ steps.cache-setup.outputs.date }}
          refcache-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      if: ${{ github.event_name == 'push' }}
      with:
        make: gh-pages
        token: ${{ github.token }}

    - name: "Archive Built Drafts"
      uses: actions/upload-artifact@v2
      with:
        path: |
          draft-*.html
          draft-*.txt
